# Generated by Django 4.0.3 on 2022-04-25 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_problems_problem_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=20)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Verdict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verdict', models.CharField(choices=[('SUCCESS', 'SUCCESS'), ('COMPILATION_ERROR', 'COMPILATION_ERROR'), ('Wrong Output', 'Wrong Output'), ('TIME LIMIT EXCEEDED', 'TIME LIMIT EXCEEDED'), ('RUNTIME ERROR', 'RUNTIME ERROR')], default='Wrong Output', max_length=20)),
                ('submittedAt', models.DateTimeField(auto_now_add=True)),
                ('problem_01', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.problems')),
            ],
        ),
    ]
