# Generated by Django 4.0.3 on 2022-06-03 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_login_verdict'),
    ]

    operations = [
        migrations.AddField(
            model_name='verdict',
            name='User_name',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='home.login'),
        ),
    ]
