# Generated by Django 4.0.3 on 2022-06-03 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_verdict_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verdict',
            name='User_name',
        ),
    ]
